# Site settings
title: Danai Vernadaki
description: Data Analytics Projects
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Danai Vernadaki
user_description: Aspiring Data Analyst |  Exploring the world of analytics
user_title: Global Trade and Market Analyst
email: danaivernadaki@gmail.com
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: https://www.linkedin.com/in/dvernadaki/
github_username:  DanaiVe
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

